spring:
  datasource:
    url: jdbc:postgresql://localhost:5412/postgres
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    path: ./logs
